feat: react router installation
wtm-medellin/iwd-2024 pull request #4
Opened 2024-02-16 15:41 UTC by lamjesus

- Listo React router
- Componente actualizado, use una función para que se pueda navegar la landing
- Habilite la navegación, comente el link de Equipo porque está en el mismo componente de sponsor pero se puede cambiar
- La función para navegar la landing tiene un smooth para suavizar el paso entre secciones 

Adicional 

1. cambie la conf de prettier porque no me funcionaba 
2. Cree un componente de error para cuando las rutas no existan

2024-02-16 15:58 UTC, mbarbag approved these changes

2024-02-16 16:48 UTC, ManuCastrillonM requested changes
Como hablamos en la reunión, porfa revierte los cambios que no tienen que ver con la navegación y mientras organizamos el pre-commit hook, haz de forma manual los ajustes de formato ejecutando en local `npm run format`

2024-02-16 16:49 UTC, ManuCastrillonM commented on src/components/ErrorPage/ErrorPage.tsx
> +      <p>Sorry, an unexpected error has occurred.</p>
Dado que el website estará en español, podrías traducir porfa este texto?

2024-02-16 16:50 UTC, ManuCastrillonM commented on src/components/ErrorPage/ErrorPage.tsx
> +      <p>Sorry, an unexpected error has occurred.</p>
En que casos va a ser mostrada esta página? 
Tal vez un mensaje como 'La ruta a la que estás intentando acceder no existe' podría dar mas claridad al usuario del error?

2024-02-16 16:53 UTC, ManuCastrillonM commented on src/components/speakers/speakers.tsx
> +    <section className="speakers" id='speakers'>
```suggestion
    <section className="speakers" id="speakers">
```

2024-02-16 16:58 UTC, ManuCastrillonM commented on src/components/navigation/navigation.tsx
> +          <Link to="/" onClick={scrollToSection('#sponsors')}>
<img width="322" alt="image" src="https://github.com/wtm-medellin/iwd-2024/assets/10585946/5838247e-9724-4ebb-88bb-4d7540939d2d">

 Podrías porfa eliminar el `text-decoration` en los `<a>`?

2024-02-24 05:35 UTC, lamjesus commented on src/components/navigation/navigation.tsx
> +          <Link to="/" onClick={scrollToSection('#sponsors')}>
deje esto porque en el figma esta,

2024-02-24 05:38 UTC, lamjesus commented on src/components/speakers/speakers.tsx
> +    <section className="speakers" id='speakers'>
ok

2024-02-24 14:49 UTC, merged